language: node_js
node_js:
  - node
dist: trusty
sudo: required

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run lint
  - xfb-run npm run test
  - npm run build
